### ISSUE TITLE
AngularJs example

### ISSUE THREAD

**Issue by bahmutov** [mojo-js/paperclip.js#155]
Can I use paperclip.js with AngularJs to replace ng-repeat for example? It would be great to replace the two- or one- way bindings with paper clip for faster rendering

**Comment by crcn** [comment]
Updated to remove comments: http://plnkr.co/edit/cAYM2Pp3QryJE7Wb6H79?p=preview

**Comment by crcn** [comment]
Also thinking about creating a paperclip directive that would allow you to embed templates directly within angular, like so:

```html
<paperclip>
  <table repeat.each={{data}}>
    <tr>
      <td>{~_0}</td>
      <td>{~_1}</td>
      <td>{~_2}</td>
      <td>{~_3}</td>
    </tr>
  </table>
</paperclip>
```
