### ISSUE TITLE
change "model" to "value" attribute on input

### ISSUE THREAD

**Issue by crcn** [mojo-js/paperclip.js#163]
This makes more sense:

```html
<input type="text" value="{{<~>name}}"></input>
```

instead of this:

```html
<input type="text" model="{{<~>name}}"></input>
```

**Comment by crcn** [comment]
implemented in `0.7.x`.

**Comment by LucaColonnello** [comment]
Sorry,
by this way I couldn't use the value for a precompiled value of an input...

How can we solve this?

**Comment by crcn** [comment]
Do you mean that something like this does not work properly?

```html
<input type="text" value="5"></input>
```
