### ISSUE TITLE
<unsafe /> element for unsafe content (fixed)

### ISSUE THREAD

**Issue by crcn** [mojo-js/paperclip.js#174]
```html
<unsafe content={{content}} />
```

instead of:

```html
{{ html: content }}
```

**Comment by crcn** [comment]
implemented in `0.7.x`.

**Comment by guilhermeaiolfi** [comment]
Hi,

great to see components coming. Is that the final form of how create components? Is it going to be possible to use templates to create components? Somehow like ractive.js. I think it's easier and would make it possible for paperclip.js to take care of bindings/cleaning/initialization for you, reducing greatly the amount of boilerplate needed.

**Comment by crcn** [comment]
Yep, `0.7.x` has been simplified to only allow web-ish components to be registered. Block bindings - `{{each:}}` and the like have been completely deprecated.

Templates in `0.7.x` can also be registered as components out of the box. Here's how you do it:

```javascript
var componentA = paperclip.template("hello {{message}}");
var componentB = paperclip.template("<componentA message='world' />", {
  components: {
    componentA: componentA
  }
});

var componentBView = componentA.view();

console.log(componentBView.toString()); // hello world
```

bindings/cleaning/initialization is pretty much handled for you if you go this route.
