### ISSUE TITLE
Migrate to a better file watcher

### ISSUE THREAD

**Issue by paulmillr** [mojo-js/paperclip.js#176]
Hey. Your file watcher [(gaze)](https://github.com/shama/gaze/issues) has 53 opened issues. Many bugs on various platforms.

Can we make a pull request that migrates the watching to [chokidar](https://github.com/paulmillr/chokidar)? Chokidar is ultra-stable and is used in many popular projects.

**Comment by crcn** [comment]
Yep, feel free to make a PR for these changes.

**Comment by crcn** [comment]
Not used anymore. Closed.
