### ISSUE TITLE
change "each" to "repeat" - should be on individual element

### ISSUE THREAD

**Issue by crcn** [mojo-js/paperclip.js#214]
```html
<ul>
	<li repeat.each={{items}} repeat.as="item">
	</li>
</ul>
```

**Comment by crcn** [comment]
This sorta thing would ideally be parsed out as something like:

```html
<ul>
    <repeat each={{items}} as="item">
      <li>
      </li>
    </repeat>
</ul>
```

And it would likely be implemented within the transpiler.

**Comment by coderangerdan** [comment]
This gets my thumbs-up.

I have an ordered list for search paging, so i have a list item for page back then multiple repeated items for each page and then an extra one at the end for page forward.

As it is, i have to create a span around the middle LI so i can repeat the child element which is actually invalid html and I would like to avoid if at all possible.

So I have:
```
<ul>
	<li><a href='#'>back</a></li>

	<span repeat.each={{items}} repeat.as {{item}}>
		<li><a href='#'>back</a></li>
	</span>

	<li><a href='#'>forward</a></li>
<ul>```

Your proposed solution would be much appreciated for this use-case.

**Comment by crcn** [comment]
This has been implemented in 3.x.
```
