### ISSUE TITLE
Partials concept

### ISSUE THREAD

**Issue by devmondo** [mojo-js/paperclip.js#230]
is there a concept like handlebars partials or even better jade or swig layouts ?
this would be really great to define stuff like headers, footers, etc... 

what i like about swig is that you can override and inherit from layouts !!!

some component like this would be great to keep the declarative syntax style
```
<partial source="./share/datepicker" bind-to-property="user.birthDate"> </partial>
```
sorry if above looks stupid 
thanks in advanced.

**Comment by crcn** [comment]
yeah totally - I think this thing might be better suited though as a separate repo such as `paperclip-partial` .

**Comment by devmondo** [comment]
this is just awesome, but how can we interact with data between those parts?

**Comment by crcn** [comment]
Hmm - not currently possible with that implementation since it was built for the backend. The layout is essentially part of the same context of the view controller that's using it, so you should be able to call methods anywhere within that template, along with the layout being used.

**Comment by devmondo** [comment]
oh great, so methods and properties flow  and available parent to child or both direction?
and when you say controller, do you mean node.js backend controller ? 

thanks again

**Comment by crcn** [comment]
Nope - the view controller / context you pass in the `view(controller)` property. And yes, properties & methods flow between children & parents. Just like variable scope.

**Comment by devmondo** [comment]
oh so context is controller, now i get it!!!
