### ISSUE TITLE
how to create dash name components or attributes

### ISSUE THREAD

**Issue by devmondo** [mojo-js/paperclip.js#235]
hi, i am trying to replicate the show component by using "show-me" instead of "show"

but i get error in console
```
Uncaught TypeError: Cannot read property 'length' of undefined
```
which by the way wont help at all if you have like a lot of stuff in the page, so you wont know what is causing the problem, so if it could give us an idea which component,attribute is causing this, it would be great :)

back to the main subject, here is my code so i assumed it is something like Angular where you capitalize letters and they will be converted to dash so showMe will be show-me, same goes for attributes ?
```
<script  >
    var pc =paperclip;
    var ShowMe = pc.Component.extend({


        update: function() {

            var show = !!this.attributes.when;

            if (this._show === show) return;

            this._show = show;

            if (show) {
                this._view = this.childTemplate.view(this.view.context);
                this.section.appendChild(this._view.render());
            } else {
                if (this._view) this._view.dispose();
                this._view = void 0;
            }
        }
    });

    // register the component
  pc.components.showMe = ShowMe;

</script>
```
```
 
    <div id="template" show-me when="{{name}}">
        Two-way binding:
        <input class="form-control" value="{{ <~>name }}" />
        <br/>
        Bind input value to name only:
        <input class="form-control" value="{{ ~>name }}" />
        <br/>

        Bind name to input value only:

        <input class="form-control" value="{{ <~name }}" />
        <br/>

        Unbound helper - don't watch for any changes:
        {{ name }}
    </div>
 
```

**Comment by crcn** [comment]
Not currently supported, but definitely an obvious thing to implement. I'll add support for converting dashes to camel case in a bit.

**Comment by crcn** [comment]
This should now work:

```html
<div attr-name="value" />
<tag-name attr="value" />
```

**Comment by devmondo** [comment]
Awesome, thanks a lot man :)

**Comment by matthewrobb** [comment]
Unfortunately the changes made to support this break being able to use regular html custom elements within a paperclip template. It would be better if the output dom maintained the dash form but at runtime it removed the dashes when looking up a component etc.

I may want to use a third party custom element inside of my templates and the changes made for this seem to have simply made it impossible.

**Comment by crcn** [comment]
Thanks for catching this - should be fixed with `2.0.3`.

**Comment by matthewrobb** [comment]
@crcn Unfortunately I am not seeing this fixed http://jsbin.com/qadutix/3/edit?html,js,output

**Comment by crcn** [comment]
forgot to bundle this up - should be good to go now: http://jsbin.com/jixuqivufe/1/edit?html,js,output
