### ISSUE TITLE
communicating between components

### ISSUE THREAD

**Issue by devmondo** [mojo-js/paperclip.js#236]
in earlier post i understood that any thing on the page will get the context of parent, but i still don't understand it very well

suppose we have a page where we have  right side bar div that has it is own context, and i have custom component A inside of it, i also have left side bar div that has it is own context, and i have custom component B inside of it, as you see left and side bar are not nested so how i can get Custom Component-A to communicate with Custom Component-B ?

another question, if child view's or custom Element's context has a property or method with names that are the same as the ones in the  Parent's context, what will happen? there will be conflict, override ?if not how i can call or set parent's context method or property from child?

thanks in advanced.

**Comment by crcn** [comment]
So, this bit isn't covered under paperclip, but in this case I'd probably implement a view-controller which as a little more structure. For example:

```javascript
var extend = require("xtend/mutable");

// ./core/views/base.js
function BaseController(properties, parentController) {

  extend(this, properties || {});
  
  this.view = this.template.view(this, {
    parent: parentController.view,
    components: {
      child: ChildComponent // not implement here
    }
  });
}

// ./views/app.js
function App() { 
  BaseController.apply(this, arguments);
}

extend(App.prototype, BaseController.prototype, {
  template: pc.template("<child controller={{children.leftSidebar}} /><br /><child controller={{children.rightSidebar}} />"),
  children: {
    leftSidebar: require("./views/leftSidebar"),
    rightSidebar: require("./views/rightSidebar")
  }
});

// ./views/leftSidebar.js
function LeftSidebar() {
  BaseController.apply(this, arguments);
}

extend(LeftSidebar.prototype, BaseController.prototype, {
  template: pc.template("left sidebar - hello {{user.name}}")
});


// ./views/rightSidebar.js
function RightSidebar() {
  BaseController.apply(this, arguments);
}

extend(RightSidebar.prototype, BaseController.prototype, {
  template: pc.template("right sidebar - hello {{user.name}}")
});


var app = new App({
  user: { name: "Clint Eastwood" }
});

// left sidebar - hello Clint Eastwood<br />right sidebar - hello Clint Eastwood<br />
document.body.appendChild(app.view.render());
```

This will ensure that child views can inherit any property from any parent controller. 

Now, if you're trying to get component A to communicate with component B in some other part of an application, I'd probably implement a a global event-bus system. Working on [mesh](https://github.com/mojo-js/mesh.js) to facilitate that. Again, putting all that logic within a view controller. 

If a child context has the same property as a parent context, then the child will have no way of accessing the parent property unless you explicitly define something like `parent.propertyThatIsShared` - you'll need to define `parent` yourself. However, accessing a `parent` property kinda breaks encapsulation - I wouldn't recommend writing something like that. 

The cleanest way to access a shared property would be to rename that property to something else in the child context.

**Comment by devmondo** [comment]
lovely detailed write up man, thanks a lot for the hints, and i love mesh :)
