### ISSUE TITLE
creating custom events and passing event object

### ISSUE THREAD

**Issue by devmondo** [mojo-js/paperclip.js#237]
suppose we are in repeater, and i have delete button for each item like below
```
<repeat each="{{items}}" as="i">
  item {{i}} <input type="button" on-click="delete()"/> <br />
</repeat>
```
in above how can i pass the item index to the delete method ? 

also how can i create custom events, for example mobile events like tab, pan, swipe, etc...

**Comment by crcn** [comment]
So, right now this is hard-coded as `index`. I'll add a feature here so you can dynamically change it youself. For example:

``` html
<repeat each="{{items}}" as="item" key="index">
</repeat>
```

**Comment by devmondo** [comment]
perfect :)

**Comment by crcn** [comment]
This should be possible now:

```html
<repeat each="{{items}}" as="i">
  item {{i}} <input type="button" onClick={{delete(i}}/> <br />
</repeat>
```

**Comment by devmondo** [comment]
awesome, thank you man :)
