### ISSUE TITLE
~>  operator example does not work

### ISSUE THREAD

**Issue by EtienneBalit** [mojo-js/paperclip.js#238]
In the "Binding Operators" section of the API page ( http://paperclipjs.com/api ),, the example doesn't do as mentionned.

Specifically, the ~> operator (binding from value to name only) seems to act as a <~> operator (two-way binding).

I didn't tested if the issue is specific to this example yet.

**Comment by crcn** [comment]
Thanks for the heads up. This should be fixed now.
