### ISSUE TITLE
Create build without parser

### ISSUE THREAD

**Issue by kupriyanenko** [mojo-js/paperclip.js#247]
Hi,

If I want to use precompiled templates via node.js, can I create custom build of paperclip.js without `parser` module, do you have other dependencies for `parser` in the code? I think it can significantly reduce the size of the file.

Thanks.

**Comment by crcn** [comment]
Yep - currently working on speccing this out actually: https://github.com/mojo-js/immutable-virtual-dom. A large chunk of the file size actually comes from `he.js` which does proper HTML entity encoding & decoding - adds > 60kb to the minified size. Tried taking the library out at one point but it cased a number of issues - haven't looked to figure out a work-around yet.

**Comment by kupriyanenko** [comment]
Good, thanks for comments, will wait for it.

If I can help with development, maybe you can share some actual issue for project.

**Comment by crcn** [comment]
Sweet - thanks for offering! Currently freezing development on parts of paperclip for a bit until immutable-virtual-dom is done - I could probably use some help on that when I get started on it in a few weeks.

**Comment by crcn** [comment]
Moving this over to the `3.x` milestone. The parser will likely be removed from the browser build by default.

**Comment by crcn** [comment]
See #280.

**Comment by crcn** [comment]
to register in the browser, do this:

```javascript
var pc = require("paperclip");
pc.compile = require("paperclip/compilers/default");
```
