### ISSUE TITLE
I'd like to contribute, please assist.

### ISSUE THREAD

**Issue by matthewrobb** [mojo-js/paperclip.js#248]
I'd like to help keep things moving along. If there's anything you'd like me to jump on feel free to assign it to me. It might also help if there were some milestones set up to make it easier to take a stab at issues.

**Comment by crcn** [comment]
Thanks for offering! Right now most of the todo items are centered around cleaning up & standardizing APIs to ensure that everything's compatible with other libraries.  I'm gonna be moving the internal vdom to a separate repo here in a bit - so any new functionality such #214, and #248 are on hold for a bit until that's done. 

I could definitely use some help however brainstorming proper APIs that are compatible with other libraries. Things like registered attributes & components for instance should be compatible with native web components in the future, and vice versa. 

Another high-priority item is to slim down paperclip of heavy dependencies such as [he.js(https://github.com/mathiasbynens/he). 

Let me know if there's anything specific that you'd like to work on!
