### ISSUE TITLE
setting up from NPM not working

### ISSUE THREAD

**Issue by Tsur** [mojo-js/paperclip.js#259]
Hi all,

as far as I know, npm will set up by default the latest version, at this moment the 3.0.1. This version has a small bug on the package.json file, the "main" field is pointing to a wrong path location:

```js
...
"//": "wrong path",
"main": "./lib/node.js",
...
"//": "should be like this",
"main": "./lib-old/node.js",
```

This works fine if I just change lib for lib-old, anyhow this version is maybe not stable yet so you may expect some issues like this, but the problem is that I do need to specify the latest stable version to npm when it should be done by default. At least, it would be nice to know from npm info which version are stable. Something like "dist-tags" on package.json with a stable o latest to 2.0.3 could make it better.

Thank you!

**Comment by crcn** [comment]
Doh! `3.0.0` isn't ready for prime time yet, and shouldn't have been published to NPM. Thanks for catching that. `3.0.0` btw isn't any different than `2.x`. Same syntax, same APIs. It's just simplified, smaller, and faster. Should be done here in a bit after I cover docs on [Mesh](http://meshjs.herokuapp.com/) (which will work nicely with paperclip).

Anyways, `2.0.4` should be the correct version on NPM. Let me know if you have anymore issues.

**Comment by crcn** [comment]
Yes, and great idea about dist tags. I'll file a bug for that and get to it asap.

**Comment by crcn** [comment]
Should all be setup under the 3.x branch: https://github.com/mojo-js/paperclip.js/commit/64d715e1efc8aa50bfa03f6874c2ec5003f487f9

**Comment by Tsur** [comment]
great, thank you so much!
