### ISSUE TITLE
(Website is down), add documentation to repo 

### ISSUE THREAD

**Issue by julienetie** [mojo-js/paperclip.js#261]
I only found out about paperclip.js today, ( I was impressed by two things, the speed and the file size) looks great so I shared the website link on twitter and then it strangely showed "Application Error".. I can not access the docs, despite the site coming back online when you get a chance, It would be really convenient if the docs were also in the repo. Thanks

**Comment by crcn** [comment]
Thanks for the heads up. I definitely plan on moving over to a GitHub page here in a bit for docs. The current website's been flakey lately. 

Website should be up, but here are the docs on GH in case it goes down again: https://github.com/mojo-js/paperclipjs.com/blob/master/lib/pages/api.md

**Comment by julienetie** [comment]
Great, thanks
