### ISSUE TITLE
How about touch events?

### ISSUE THREAD

**Issue by LucaColonnello** [mojo-js/paperclip.js#272]
Hi,
thank you for this great library!

But, what about touch events!
I think that we couldn't use hammer because of the dom replacement doing with virtual dom diff.

How can we solve?

Thanks in advice

**Comment by crcn** [comment]
Paperclip actually doesn't replace *any* elements once they've been added to the DOM. The library only mutates text blocks and element attributes, so you can do ahead and use [Hammer.js](http://hammerjs.github.io/), jQuery, or any other library without a problem.

Here's a clean way to use [Hammer.js](http://hammerjs.github.io/) though:

```javascript
var attrs = {
  onPan: pc.Attribute.extend({
    initialize: function () {
      var hammertime = new Hammer(myElement, myOptions);
      hammertime.on('pan', function(ev) {
        this.value.evaluate(this.view);
      }.bind(this));
    }
  })
};

var tpl = pc.template("<button onPan={{handlePan}}></button>", { attributes: attrs });
```

**Comment by LucaColonnello** [comment]
Thank you for your explaination..
That's very good!!

Il giorno gio 9 lug 2015 alle ore 15:31 Craig Condon <
notifications@github.com> ha scritto:

**Comment by LucaColonnello** [comment]
Sorry,
but the handle is called at first render time, not when the event is dispatched.

Why???

http://jsbin.com/rupilasibi/2/edit?html,js,output

**Comment by crcn** [comment]
Fixed. See #274.
