### ISSUE TITLE
Nested components do not share parent model

### ISSUE THREAD

**Issue by AutoSponge** [mojo-js/paperclip.js#275]
I noticed this in a few situations, however I think this example is the most simple and clear.

https://jsbin.com/bekojetoke/edit?js,console,output

Nested components do not modify the parent model (assume they modify a child model) but the child model is not accessible from the `view.get()`. I'm suggesting either:

1 - the model is shared (so repeated elements can share state) 
2 - the child elements' models are accessible from the parent (although this would make it very difficult to sync state)
3 - the parent scope is accessible from the component (e.g., `<component onClick={{ parent.selected = item }}>` )

**Comment by AutoSponge** [comment]
I created a small patch that solves this, I'm interested if you want to merge it:

inside the repeat component:
```javascript
//...
    _each(source, function(model, i) {

      if (name) {
        properties = {};
        properties.parent = self.view.context; //new!
        properties[key]  = i;
        properties[name] = model;
      } else {
        properties = model;
      }
//...
```

In the template
```html
<repeat each="12345" as="item">
    <button class="{{ parent.item_selected === item ? 'selected' : ''}}"
        onEnter="{{ log(item_selected) }}"
        onClick="{{ item_selected = item}}" tabIndex="0">{{ item }}</button>
</repeat>
```

**Comment by crcn** [comment]
Sharing the same context within a `repeat` block seems to be the right approach. It should also speed things up significantly. 

In the meantime, a good option for this sort of think might be to add an explicit `select` method in the view controller. Like so:

https://jsbin.com/xeteyokawu/edit?js,console,output

**Comment by AutoSponge** [comment]
This may be related then, because your solution doesn't work. Notice that the selected class is never applied. The 'selected' button should have a blue background. This is what the other issue I opened is for. The data changes but the repeated element will skip re-rendering. I think it's caused by this line: https://github.com/mojo-js/paperclip.js/blob/master/lib/components/repeat.js#L66

**Comment by crcn** [comment]
Yep, definitely related to #267. Closing as a duplicate.

**Comment by crcn** [comment]
Yep definitely related, but more of a design bug. Will fix for `3.x`.

**Comment by crcn** [comment]
Closing since this should now be fixed.
