### ISSUE TITLE
3.x Event Handlers

### ISSUE THREAD

**Issue by AutoSponge** [mojo-js/paperclip.js#296]
What am I doing wrong here? http://jsbin.com/mapica/1/edit?js,output

With the first template, I get the correct behavior. But when I try to pass arguments to the function in 2.x style, the function fires repeatedly (I assume with the animationFrame) and it breaks.

**Comment by crcn** [comment]
Fixed: http://jsbin.com/lazolecoyi/edit?js,output

`3.x` event handlers now take a reference to a function. So instead of this:

````html
<button onclick="{{ handle(someProp) }}" />
````

You'd do this:

```html
<button onclick="{{ handle.bind(this, someProp }}" />
```

I've moved the paperclip documentation to this repo and cleaned up some old stuff. I'll continue to add more docs here in the next few days.

**Comment by AutoSponge** [comment]
Thanks, that makes sense.

My designers are really going to miss writing expressions in handlers:

```javascript
<div class="{{ active ? '' : 'hidden' }}" onClick="{{ active = !active }}">TOGGLE ME</div>
```

I'll can look at the documentation this week and create some bins/gists. Personally it really helps me learn something to see it working in a REPL. However, the current examples are all focused on fast render/benchmarks and not user interaction or behavior.

**Comment by crcn** [comment]
I totally agree that some of the examples aren't completely fleshed out. I've been meaning to create a few working applications under paperclip. 

I'll be on vacation next week so I'll have more time to work on some good examples. 👍
